name: Solar-System
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{ vars.MONGO_URI}}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
  unit-testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os}}
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     - name: Setup Node.js environment - ${{ matrix.node-version }}
       uses: actions/setup-node@v6.2.0
       with:
        node-version: ${{ matrix.node-version}}
     - name: NPM Cache
       uses: actions/cache@v5.0.3
       with:
        path: node_modules
        key: ${{ runner.os}}-node_modules-${{ hashFiles('package.lock.json')}}
     - name: Install Dependencies
       run: npm install
     - name: Unit Testing
       id: node-js-unit-test
       run: npm test
     - name: Archive Test Result
      #  if: failure() && (steps.node-js-unit-test.outcome == 'failure' || steps.node-js-unit-test == 'success') Skip if previous step is failue
       if: always()
       uses: actions/upload-artifact@v7.0.0
       with:
        name: Test-Artifact
        path: test-results.xml
  code-coverage:
    needs: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment - ${{ matrix.node-version }}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node-version}}
      - name: NPM Cache
        uses: actions/cache@v5.0.3
        with:
          path: node_modules
          key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json')}}
      - name: Install Dependencies
        run: npm install
      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage
      - name: Upload a Test Archive Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Code-Coverage-Artifact
          path: coverage
          retention-days: 5
  docker:
    needs: [unit-testing, code-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}