name: Solar-System
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
  unit-testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 19, 20]
        exclude:
          - node-version: 19
    runs-on: ${{ matrix.os}}
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     - name: Setup Node.js environment - ${{ matrix.node-version }}
       uses: actions/setup-node@v6.2.0
       with:
        node-version: ${{ matrix.node-version}}
     - name: Install Dependencies
       run: npm install
     - name: Unit Testing
       run: npm test
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v7.0.0
       with:
        name: Test-Artifact
        path: test-results.xml
