name: Solar-System
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
  unit-testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os}}
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     - name: Setup Node.js environment - ${{ matrix.node-version }}
       uses: actions/setup-node@v6.2.0
       with:
        node-version: ${{ matrix.node-version}}
     - name: Install Dependencies
       run: npm install
     - name: Unit Testing
       id: node-js-unit-test
       run: npm test
     - name: Archive Test Result
       if: failure() && (steps.node-js-unit-test.outcome == 'failure' || steps.node-js-unit-test == 'success')
       uses: actions/upload-artifact@v7.0.0
       with:
        name: Test-Artifact
        path: test-results.xml
  code-coverage:
    needs: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment - ${{ matrix.node-version }}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install Dependencies
        run: npm install
      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage
      - name: Upload a Test Archive Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Code-Coverage-Artifact
          path: coverage
          retention-days: 5


        
